-- Create a table for templates
create table templates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  image_url text,
  tags text[], -- Array of strings
  github_repo_url text, -- Source code URL
  demo_url text -- Live demo URL
);

-- Insert some sample data
insert into templates (title, description, image_url, tags)
values
  ('단어 퀴즈 마스터', '학생들이 재미있게 영단어를 학습할 수 있는 퀴즈 앱입니다. 엑셀로 문제만 올리면 끝!', 'https://placehold.co/600x400/e8f5e9/4caf50?text=Word+Quiz', ARRAY['영어', '퀴즈', '초/중/고']),
  ('우리 반 자리바꾸기', '공정하고 빠른 자리 배치 프로그램. 남녀 성비, 시력 보호석 설정 가능.', 'https://placehold.co/600x400/e3f2fd/2196f3?text=Seat+Change', ARRAY['학급운영', '유틸리티']),
  ('급식 투표 게시판', '오늘의 급식 메뉴를 확인하고 맛있는 메뉴에 투표하는 소통 공간입니다.', 'https://placehold.co/600x400/fff3e0/ff9800?text=Lunch+Vote', ARRAY['급식', '소통', '자치활동']),
  ('독서 마라톤 기록장', '학생들의 독서 활동을 기록하고 통계를 보여주는 디지털 독서록.', 'https://placehold.co/600x400/f3e5f5/9c27b0?text=Reading+Log', ARRAY['국어', '독서', '포트폴리오']);

-- Create a table for users (Custom ID/Password login and OAuth)
create table users (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text unique, -- Login ID (nullable for OAuth users)
  email text unique, -- Email (for OAuth users)
  nickname text, -- Display Name
  password_hash text, -- Password (nullable for OAuth users)
  oauth_provider text, -- 'google', 'github', or null for credentials
  oauth_id text, -- OAuth provider's user ID
  nickname_set boolean default false -- Whether nickname has been set
);

-- Create unique index for OAuth users
create unique index users_oauth_provider_id_idx on users(oauth_provider, oauth_id) where oauth_provider is not null;
